# Generated by Django 3.2.16 on 2024-03-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
