# Generated by Django 3.2.16 on 2024-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['client', 'service'], name='services_su_client__f485a9_idx'),
        ),
    ]
